### ISSUE TITLE
Generating priv_validator_key  from seed words used to initiate ledger

### ISSUE THREAD

**Issue by asmodat** [tendermint/ledger-validator-app#17]
I would want to use seed words that I sued to initiate ledger with to create a softsign priv_validator_key file or to use those words to initiate youbi later, how can I do that ?

I found the following info so far
```
 Step 1: retrieve the 512 bits master seed from bip39/bip32 24 words 
      Step 2: apply SLIP10 initialization to derive master Ed25519 key and chain code
      Step 3: Apply "BIP32-Ed25519 Hierarchical Deterministic Keys over a Non-linear Keyspace" paper from Dmitry Khovratovich and Jason Law
```

so what I did so far is 
1. generated a bip39
 var bip39 = new Bip39("... bla bla ..")
2. used that to derive key
var derivedKey = Ed25519HdKeyGen.DerivePath("m/44'/118'/0'/0'/0'", bip39.SeedBytes);

Now I have Key and Chain Code, but no idea what to do next

**Comment by asmodat** [comment]
Solution I tried but didn't ended up working

if you want to generate `priv_validator_key `

for example:
```
{
  "pub_key": {
    "type": "tendermint/PubKeyEd25519",
    "value": "BASE64_XXXXXXXXXX_32B"
  },
  "priv_key": {
    "type": "tendermint/PrivKeyEd25519",
    "value": "BASE64_XXXXXXXXXX_64B"
  }
}
```

1. generate bip39
var bip39 = new Bip39("... bla bla ..")

2. derive a key
derivedKey = Ed25519HdKeyGen.DerivePath("m/44'/118'/0'/0'/0'", bip39.SeedBytes);

that will give you Key and Chaincode, ignore the chain code,

3. use key to generate public key

var pubKey = Ed25519HdKeyGen.GetPublicKey(derivedKey.Key);

4. Encode with base64

pub_key = pubKey.ToBase64String();
priv_key = derivedKey.Key.Combine(pubKey).ToBase64String();


# Notes
* address field is not required 
* more info can be also found in [this issue](https://github.com/tendermint/tendermint/issues/3320#issuecomment-471567939)

**Comment by asmodat** [comment]
Working script to receive privat key, no need to do tmkms import as it outputs base64: https://github.com/KiraCore/KB/blob/master/Cosmos/Scripts/tmkms-softsign-recovery-from-seed.py

**Comment by jleni** [comment]
would you mind creating a PR for this? Ideally including a brief markdown document explaining how to use it? I think it would be great to have it as part of this repository.

**Comment by asmodat** [comment]
To this repo or some other ?

I think https://github.com/tendermint/tendermint/tree/master/tools would be good

**Comment by jleni** [comment]
That would work too.
Anyway, just FYI. we will be restructuring Ledger related repos in the next couple of weeks to simplify development workflow, etc.

**Comment by asmodat** [comment]
Done as recommended: https://github.com/tendermint/tendermint/pull/4528/files
